//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMovementBase"",
            ""id"": ""47d2a098-8a75-4af0-9ede-13791b0de08e"",
            ""actions"": [
                {
                    ""name"": ""MoveDirection"",
                    ""type"": ""Value"",
                    ""id"": ""f3ab1007-4776-4274-897f-710e43aa676e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookDirection"",
                    ""type"": ""Value"",
                    ""id"": ""057127b7-4ce1-4fa7-8753-33c9550cf63c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchPlacingMode"",
                    ""type"": ""Button"",
                    ""id"": ""e94a9ced-c2a7-41df-b0e5-61da6caf3a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a90943ca-41d5-468d-b7b1-dbd6a02c251f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02986b1e-ffdf-4ee6-be4b-0fd4d901fd71"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LookDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055bf063-67ab-4a59-9851-e8c26afdbacd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SwitchPlacingMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerShooting"",
            ""id"": ""1df8e6e0-3bde-44f2-940b-3dd978abc25d"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""12582d6a-ef65-4df1-bd16-e154ee3fcce1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""bc468056-a877-45ac-9c23-11182f62b52b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1023d12c-2283-46ca-a361-673b083d3604"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""204668ae-c2b5-4c49-995d-b139fa5c3f42"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NextWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerPlacing"",
            ""id"": ""d2d16597-c379-4913-8fb8-5864865db41b"",
            ""actions"": [
                {
                    ""name"": ""Buid"",
                    ""type"": ""Button"",
                    ""id"": ""09c40dab-6cdf-4ab0-a858-47d8655ffc1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextTurret"",
                    ""type"": ""Button"",
                    ""id"": ""7ebe3ef9-a882-470d-bef2-9c53faef6868"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aeb34afa-1d37-456f-8098-dcb9dadbd46a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Buid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ecd5b8f-8f9e-48f2-934b-b8604b226910"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerMovementBase
        m_PlayerMovementBase = asset.FindActionMap("PlayerMovementBase", throwIfNotFound: true);
        m_PlayerMovementBase_MoveDirection = m_PlayerMovementBase.FindAction("MoveDirection", throwIfNotFound: true);
        m_PlayerMovementBase_LookDirection = m_PlayerMovementBase.FindAction("LookDirection", throwIfNotFound: true);
        m_PlayerMovementBase_SwitchPlacingMode = m_PlayerMovementBase.FindAction("SwitchPlacingMode", throwIfNotFound: true);
        // PlayerShooting
        m_PlayerShooting = asset.FindActionMap("PlayerShooting", throwIfNotFound: true);
        m_PlayerShooting_Shoot = m_PlayerShooting.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerShooting_NextWeapon = m_PlayerShooting.FindAction("NextWeapon", throwIfNotFound: true);
        // PlayerPlacing
        m_PlayerPlacing = asset.FindActionMap("PlayerPlacing", throwIfNotFound: true);
        m_PlayerPlacing_Buid = m_PlayerPlacing.FindAction("Buid", throwIfNotFound: true);
        m_PlayerPlacing_NextTurret = m_PlayerPlacing.FindAction("NextTurret", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovementBase
    private readonly InputActionMap m_PlayerMovementBase;
    private List<IPlayerMovementBaseActions> m_PlayerMovementBaseActionsCallbackInterfaces = new List<IPlayerMovementBaseActions>();
    private readonly InputAction m_PlayerMovementBase_MoveDirection;
    private readonly InputAction m_PlayerMovementBase_LookDirection;
    private readonly InputAction m_PlayerMovementBase_SwitchPlacingMode;
    public struct PlayerMovementBaseActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerMovementBaseActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveDirection => m_Wrapper.m_PlayerMovementBase_MoveDirection;
        public InputAction @LookDirection => m_Wrapper.m_PlayerMovementBase_LookDirection;
        public InputAction @SwitchPlacingMode => m_Wrapper.m_PlayerMovementBase_SwitchPlacingMode;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovementBase; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementBaseActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementBaseActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementBaseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementBaseActionsCallbackInterfaces.Add(instance);
            @MoveDirection.started += instance.OnMoveDirection;
            @MoveDirection.performed += instance.OnMoveDirection;
            @MoveDirection.canceled += instance.OnMoveDirection;
            @LookDirection.started += instance.OnLookDirection;
            @LookDirection.performed += instance.OnLookDirection;
            @LookDirection.canceled += instance.OnLookDirection;
            @SwitchPlacingMode.started += instance.OnSwitchPlacingMode;
            @SwitchPlacingMode.performed += instance.OnSwitchPlacingMode;
            @SwitchPlacingMode.canceled += instance.OnSwitchPlacingMode;
        }

        private void UnregisterCallbacks(IPlayerMovementBaseActions instance)
        {
            @MoveDirection.started -= instance.OnMoveDirection;
            @MoveDirection.performed -= instance.OnMoveDirection;
            @MoveDirection.canceled -= instance.OnMoveDirection;
            @LookDirection.started -= instance.OnLookDirection;
            @LookDirection.performed -= instance.OnLookDirection;
            @LookDirection.canceled -= instance.OnLookDirection;
            @SwitchPlacingMode.started -= instance.OnSwitchPlacingMode;
            @SwitchPlacingMode.performed -= instance.OnSwitchPlacingMode;
            @SwitchPlacingMode.canceled -= instance.OnSwitchPlacingMode;
        }

        public void RemoveCallbacks(IPlayerMovementBaseActions instance)
        {
            if (m_Wrapper.m_PlayerMovementBaseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementBaseActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementBaseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementBaseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementBaseActions @PlayerMovementBase => new PlayerMovementBaseActions(this);

    // PlayerShooting
    private readonly InputActionMap m_PlayerShooting;
    private List<IPlayerShootingActions> m_PlayerShootingActionsCallbackInterfaces = new List<IPlayerShootingActions>();
    private readonly InputAction m_PlayerShooting_Shoot;
    private readonly InputAction m_PlayerShooting_NextWeapon;
    public struct PlayerShootingActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerShootingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_PlayerShooting_Shoot;
        public InputAction @NextWeapon => m_Wrapper.m_PlayerShooting_NextWeapon;
        public InputActionMap Get() { return m_Wrapper.m_PlayerShooting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerShootingActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerShootingActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerShootingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerShootingActionsCallbackInterfaces.Add(instance);
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @NextWeapon.started += instance.OnNextWeapon;
            @NextWeapon.performed += instance.OnNextWeapon;
            @NextWeapon.canceled += instance.OnNextWeapon;
        }

        private void UnregisterCallbacks(IPlayerShootingActions instance)
        {
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @NextWeapon.started -= instance.OnNextWeapon;
            @NextWeapon.performed -= instance.OnNextWeapon;
            @NextWeapon.canceled -= instance.OnNextWeapon;
        }

        public void RemoveCallbacks(IPlayerShootingActions instance)
        {
            if (m_Wrapper.m_PlayerShootingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerShootingActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerShootingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerShootingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerShootingActions @PlayerShooting => new PlayerShootingActions(this);

    // PlayerPlacing
    private readonly InputActionMap m_PlayerPlacing;
    private List<IPlayerPlacingActions> m_PlayerPlacingActionsCallbackInterfaces = new List<IPlayerPlacingActions>();
    private readonly InputAction m_PlayerPlacing_Buid;
    private readonly InputAction m_PlayerPlacing_NextTurret;
    public struct PlayerPlacingActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerPlacingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Buid => m_Wrapper.m_PlayerPlacing_Buid;
        public InputAction @NextTurret => m_Wrapper.m_PlayerPlacing_NextTurret;
        public InputActionMap Get() { return m_Wrapper.m_PlayerPlacing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerPlacingActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerPlacingActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerPlacingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerPlacingActionsCallbackInterfaces.Add(instance);
            @Buid.started += instance.OnBuid;
            @Buid.performed += instance.OnBuid;
            @Buid.canceled += instance.OnBuid;
            @NextTurret.started += instance.OnNextTurret;
            @NextTurret.performed += instance.OnNextTurret;
            @NextTurret.canceled += instance.OnNextTurret;
        }

        private void UnregisterCallbacks(IPlayerPlacingActions instance)
        {
            @Buid.started -= instance.OnBuid;
            @Buid.performed -= instance.OnBuid;
            @Buid.canceled -= instance.OnBuid;
            @NextTurret.started -= instance.OnNextTurret;
            @NextTurret.performed -= instance.OnNextTurret;
            @NextTurret.canceled -= instance.OnNextTurret;
        }

        public void RemoveCallbacks(IPlayerPlacingActions instance)
        {
            if (m_Wrapper.m_PlayerPlacingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerPlacingActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerPlacingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerPlacingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerPlacingActions @PlayerPlacing => new PlayerPlacingActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerMovementBaseActions
    {
        void OnMoveDirection(InputAction.CallbackContext context);
        void OnLookDirection(InputAction.CallbackContext context);
        void OnSwitchPlacingMode(InputAction.CallbackContext context);
    }
    public interface IPlayerShootingActions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnNextWeapon(InputAction.CallbackContext context);
    }
    public interface IPlayerPlacingActions
    {
        void OnBuid(InputAction.CallbackContext context);
        void OnNextTurret(InputAction.CallbackContext context);
    }
}
